# Import the relevant libraries

In [ ]:
import numpy as np # Import the NumPy library, essential for numerical operations in Python, especially with arrays.

# Declaring scalars, vectors, and matrices

## Scalars

In [ ]:
s = 5 # A scalar is a single numerical value. Here, 's' is assigned the scalar value 5.

In [ ]:
s # Display the value of the scalar 's'.

5

## Vectors

In [ ]:
# A vector is a 1D array of numbers.
v = np.array([5,-2,4]) # By default, a 1D array created with NumPy will behave as a row vector.

In [ ]:
v # Display the vector 'v'.

array([ 5, -2,  4])

## Matrices

In [ ]:
# A matrix is a 2D array of numbers.
m = np.array([[5,12,6],[-3,0,14]]) # 'm' is a 2x3 matrix with two rows and three columns.

In [ ]:
m # Display the matrix 'm'.

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [ ]:
type(s) # Check the data type of the scalar 's'. It's a standard Python integer.

int

In [ ]:
type(v) # Check the data type of the vector 'v'. It's a NumPy ndarray (n-dimensional array).

numpy.ndarray

In [ ]:
type(m) # Check the data type of the matrix 'm'. It's also a NumPy ndarray.

numpy.ndarray

In [ ]:
s_array = np.array(5) # Create a NumPy array from a scalar. This makes it a 0-dimensional NumPy array.

In [ ]:
type(s_array) # Verify the type of 's_array' is a NumPy ndarray.

numpy.ndarray

## Data shapes

In [ ]:
m.shape # Get the shape of the matrix 'm'. It returns a tuple (rows, columns).

(2, 3)

In [ ]:
v.shape # Get the shape of the vector 'v'. For a 1D array, it returns a tuple with the number of elements.

(3,)

In [ ]:
#s.shape #uncomment to see the error

In [ ]:
s_array.shape  # it gives empty paranthesis bcz a scalar is a 0-dimentional objects don't have shape.

()

## Creating a column vector

In [ ]:
v.reshape(1,3) # Reshape the 1D vector 'v' into a 1x3 row vector (2D array).

array([[ 5, -2,  4]])

In [ ]:
v.reshape(3,1) # Reshape the 1D vector 'v' into a 3x1 column vector (2D array).

array([[ 5],
       [-2],
       [ 4]])

In [ ]:
m+s # Demonstrates broadcasting: the scalar 's' is added to every element of the matrix 'm'.

array([[10, 17, 11],
       [ 2,  5, 19]])

In [ ]:
m+s_array # Similar to adding a scalar, the 0-dimensional NumPy array 's_array' is broadcasted to 'm'.

array([[10, 17, 11],
       [ 2,  5, 19]])

In [ ]:
v+s # The scalar 's' is broadcasted and added to each element of the vector 'v'.

array([10,  3,  9])

In [ ]:
v # Display the original vector 'v' to show it remains unchanged.

array([ 5, -2,  4])

In [ ]:
v+s_array # The 0-dimensional NumPy array 's_array' is broadcasted and added to each element of the vector 'v'.

array([10,  3,  9])

In [ ]:
m+v # Demonstrates broadcasting: the vector 'v' is added row-wise to the matrix 'm'.

array([[10, 10, 10],
       [ 2, -2, 18]])