# Scalars, Vectors, and Matrices

This notebook introduces the fundamental building blocks of linear algebra:
scalars, vectors, and matrices. These objects are used to represent data
and perform mathematical operations in machine learning.


In [1]:
# Import NumPy for numerical operations
import numpy as np


## Scalars

A scalar is a single numerical value. In programming, it is represented
as a normal number.


In [2]:
# Two scalar values
temperature = 30
growth_rate = 1.05

# Basic arithmetic with scalars
scaled_value = temperature * growth_rate
scaled_value


31.5

## Vectors

A vector is an ordered list of numbers. In NumPy, vectors are represented
as one-dimensional arrays.


In [3]:
# Creating a vector
height_vector = np.array([150, 160, 170, 180])

# Display the vector and its shape
height_vector, height_vector.shape


(array([150, 160, 170, 180]), (4,))

## Vector Operations

We can perform element-wise operations on vectors.


In [4]:
# Create another vector
weight_vector = np.array([50, 60, 65, 70])

# Element-wise addition
combined = height_vector + weight_vector
combined


array([200, 220, 235, 250])

## Matrices

A matrix is a two-dimensional collection of numbers arranged in rows and columns.


In [5]:
# Creating a matrix
student_scores = np.array([
    [80, 85, 90],
    [70, 75, 78],
    [88, 92, 95]
])

student_scores


array([[80, 85, 90],
       [70, 75, 78],
       [88, 92, 95]])

## Matrix Shape

The shape of a matrix tells us how many rows and columns it has.


In [6]:
student_scores.shape


(3, 3)

## Machine Learning Connection

In machine learning:
- Scalars represent single values like learning rate or bias.
- Vectors represent data points (one row of a dataset).
- Matrices represent entire datasets where rows are samples and columns are features.


In [7]:
# Example: dataset with 3 students and 3 features
dataset = np.array([
    [170, 65, 80],   # height, weight, score
    [160, 55, 75],
    [180, 75, 90]
])

dataset


array([[170,  65,  80],
       [160,  55,  75],
       [180,  75,  90]])