# Import the relevant libraries

In [1]:
import numpy as np # Import the numpy library, commonly aliased as 'np', for numerical operations.

## Creating a tensor

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]]) # Create a 2x3 NumPy array (matrix) named m1.
m1 # Display the matrix m1.

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]]) # Create another 2x3 NumPy array (matrix) named m2.
m2 # Display the matrix m2.

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
t = np.array([m1,m2]) # Create a 3D NumPy array (tensor) by stacking m1 and m2 along a new axis.

In [5]:
t # Display the tensor t.

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Checking its shape

In [6]:
t.shape # Get and display the shape of the tensor t. It is a 2x2x3 object, meaning it contains 2 matrices of 2x3 each.

(2, 2, 3)

## Manually creating a tensor

In [7]:
t_manual = np.array([[[ 5, 12,  6], [-3,  0, 14]], [[ 9,  8,  7], [ 1,  3, -5]]]) # Manually create a 3D NumPy array (tensor) with specified values.

In [8]:
t_manual # Display the manually created tensor t_manual.

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [9]:
# This comment explains that while we're manually creating tensors here for theoretical understanding,
# in real-world scenarios, tensors are typically generated by loading, transforming, and preprocessing data.