# Import the relevant libraries

In [ ]:
import numpy as np # Import the numpy library for numerical operations, especially with arrays and matrices.

## Addition

In [ ]:
m1 = np.array([[5,12,6],[-3,0,14]]) # Define the first 2x3 matrix m1
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [ ]:
m2 = np.array([[9,8,7],[1,3,-5]]) # Define the second 2x3 matrix m2
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [ ]:
m1 + m2 # Perform element-wise addition of matrix m1 and m2

array([[14, 20, 13],
       [-2,  3,  9]])

## Difference

### Example 1

In [ ]:
m3 = np.array([[5,3],[-2,4]]) # Define the first 2x2 matrix m3
m4 = np.array([[7,-5],[3,8]]) # Define the second 2x2 matrix m4

In [ ]:
m3 # Display matrix m3

array([[ 5,  3],
       [-2,  4]])

In [ ]:
m4 # Display matrix m4

array([[ 7, -5],
       [ 3,  8]])

In [ ]:
m3 - m4 # Perform element-wise subtraction of matrix m4 from m3

array([[-2,  8],
       [-5, -4]])

### Example 2

In [ ]:
m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.1]]) # Define the first 3x2 matrix m5
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [ ]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]]) # Define the second 3x2 matrix m6
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [ ]:
m5 - m6 # Perform element-wise subtraction of matrix m6 from m5

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

## Adding vectors together

In [ ]:
v1 = np.array([1,2,3,4,5]) # Define the first 1D array (vector) v1
v2 = np.array([5,4,3,2,1]) # Define the second 1D array (vector) v2

In [ ]:
v1 + v2 # Perform element-wise addition of vector v1 and v2

array([6, 6, 6, 6, 6])

In [ ]:
v1 - v2 # Perform element-wise subtraction of vector v2 from v1

array([-4, -2,  0,  2,  4])