## Why Tensors Matter

Machine learning models operate on tensors internally.
Understanding their shapes and dimensions is essential
when working with neural networks.


In [1]:
import numpy as np


## Vector Addition

Two vectors can be added if they have the same length.
The operation is performed element-wise.


In [2]:
# Define two vectors
sales_week1 = np.array([100, 150, 200])
sales_week2 = np.array([80, 120, 180])

# Add the vectors
total_sales = sales_week1 + sales_week2
total_sales


array([180, 270, 380])

## Vector Subtraction

Subtraction is also element-wise and requires equal dimensions.


In [3]:
# Difference in sales
sales_difference = sales_week1 - sales_week2
sales_difference


array([20, 30, 20])

## Matrix Addition

Matrices can be added only if they have the same shape.


In [4]:
# Two matrices
matrix_A = np.array([[10, 20], [30, 40]])
matrix_B = np.array([[5, 15], [25, 35]])

# Matrix addition
matrix_A + matrix_B


array([[15, 35],
       [55, 75]])