# Import the relevant libraries

In [18]:
import numpy as np # Import the NumPy library for numerical operations

## Addition

### Addition of scalars

In [19]:
# This cell demonstrates basic arithmetic addition of two scalar (single) numbers.
5 + 5

10

In [20]:
# This cell demonstrates basic arithmetic subtraction of two scalar (single) numbers.
10 - 4

6

### Addition of matrices

In [21]:
# Define a 2x3 matrix m1 using NumPy array
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [22]:
# Define a 2x2 matrix m3 using NumPy array
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [23]:
# Attempt to add matrices m1 and m3 (this will cause an error due to incompatible shapes)
# m1 + m3    #uncomment to see the error

### Addition of vectors

In [24]:
# Define a vector v1 using NumPy array
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [25]:
# Define a vector v3 using NumPy array
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [26]:
# Attempt to add vectors v1 and v3 (this will cause an error due to incompatible shapes)
# v1+v3   #uncomment to see the error

### Exceptions (addition with a scalar)

In [27]:
# Display matrix m1
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [28]:
# Add a scalar to matrix m1 (broadcasts the scalar to each element)
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [29]:
# Display vector v1
v1

array([1, 2, 3, 4, 5])

In [30]:
# Add a scalar to vector v1 (broadcasts the scalar to each element)
v1 + 1

array([2, 3, 4, 5, 6])

In [31]:
# Add a scalar array to matrix m1 (broadcasts the scalar to each element)
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [32]:
# Add a scalar array to vector v1 (broadcasts the scalar to each element)
v1 + np.array([1])

array([2, 3, 4, 5, 6])