# Transpose of a Matrix

The transpose of a matrix is obtained by swapping its rows and columns.
This operation is widely used in linear algebra and machine learning.

In [1]:
import numpy as np

## Original Matrix

In [2]:
data_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

data_matrix


array([[1, 2, 3],
       [4, 5, 6]])

## Transposed Matrix

In [3]:
transposed_matrix = data_matrix.T
transposed_matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

## Why Transpose is Useful

Transpose is often used when switching between row-wise and column-wise representations,
especially in machine learning algorithms.

## Machine Learning Connection

Transpose is used when switching between:
- Features × Samples
- Samples × Features

In [4]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

X, X.T

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 3, 5],
        [2, 4, 6]]))