# Dot Product of Matrices

Matrix multiplication combines rows of the first matrix with columns
of the second matrix. This operation is fundamental to machine learning.

In [1]:
import numpy as np

## Two Matrices

In [2]:
matrix_A = np.array([
    [1, 2],
    [3, 4]
])

matrix_B = np.array([
    [2, 0],
    [1, 2]
])

matrix_A, matrix_B

(array([[1, 2],
        [3, 4]]),
 array([[2, 0],
        [1, 2]]))

## Matrix Multiplication

In [3]:
result = matrix_A @ matrix_B
result

array([[ 4,  4],
       [10,  8]])

## Why This Matters

Matrix multiplication is used in neural networks,
linear regression, and most machine learning algorithms.