# Dot Product of Matrices

Matrix multiplication combines rows of the first matrix with columns
of the second matrix. This operation is fundamental to machine learning.

In [ ]:
import numpy as np

## Two Matrices

In [ ]:
matrix_A = np.array([
    [1, 2],
    [3, 4]
])

matrix_B = np.array([
    [2, 0],
    [1, 2]
])

matrix_A, matrix_B

(array([[1, 2],
        [3, 4]]),
 array([[2, 0],
        [1, 2]]))

## Matrix Multiplication

In [ ]:
result = matrix_A @ matrix_B
result

array([[ 4,  4],
       [10,  8]])

##### In Python (NumPy):

`A @ B`


means:

**Matrix multiplication**

It is the same as:

`np.dot(A, B)`


but:

- @ is clearer

- It works only for matrices & tensors

- It avoids mistakes with element-wise *

In machine learning:

- `X @ W `is how models compute predictions

- Neural networks are basically chains of @

So @ is the language of ML mathematics inside Python.

## Why This Matters

Matrix multiplication is used in neural networks,
linear regression, and most machine learning algorithms.

## Machine Learning Connection

Neural networks perform matrix multiplication between:
- Input data
- Weight matrices

In [ ]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

W = np.array([[0.5, 0.2],
              [0.1, 0.3]])

X @ W

array([[0.7, 0.8],
       [1.9, 1.8],
       [3.1, 2.8]])